on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: golangci-lint
jobs:
  golangci:
    strategy:
      matrix:
        go-version:
          - "1.20"
          - "1.21"
          - "oldstable"
          - "stable"
    name: lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          version: v2.5
      - name: test
        run: make test
